/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package chatvader.pkg0;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.*;
import javax.swing.*;
import javax.swing.text.AttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
/**
 *
 * @author salimbouassida
 */

public class NewJFrame extends javax.swing.JFrame {
    private String persona="Vader";
    private String start="<"+persona+">"+"Greetings";
    private String output;
    private int count=0;
    private String input;
   
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        
        initComponents();
       
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputbox = new javax.swing.JTextField();
        switcher = new javax.swing.JToggleButton();
        send = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatbox = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enter(evt);
            }
        });
        jPanel1.add(inputbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 365, 498, 49));

        switcher.setText("Switch");
        switcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchpersona(evt);
            }
        });
        jPanel1.add(switcher, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 90, 30));

        send.setText("Send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        jPanel1.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 365, 100, 40));

        chatbox.setEditable(false);
        jScrollPane1.setViewportView(chatbox);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 490, 300));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatvader/pkg0/Header.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatvader/pkg0/space.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 740, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 718, 447));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
  try {
               String input=((inputbox.getText()).toLowerCase()).trim();
               chat(input);
               
            } catch (Exception ex) {
               System.out.print("Error22");}
         
        inputbox.setText("");
        inputbox.requestFocus();        

                   }//GEN-LAST:event_sendActionPerformed

    private void switchpersona(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchpersona
if (persona=="Vader")
persona ="Young";
else persona="Vader";
inputbox.requestFocus();
// TODO add your handling code here:
    }//GEN-LAST:event_switchpersona

    private void enter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enter
if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        

      
      try {
               String input=((inputbox.getText()).toLowerCase()).trim();
               chat(input);
               
            } catch (Exception ex) {
               System.out.print("Error22");}
         
        inputbox.setText("");
        inputbox.requestFocus();        

    }//GEN-LAST:event_enter
    }
    public void  chat(String input){
       
        StyledDocument chat = chatbox.getStyledDocument();
        output=bot.Bot(input);
        
try
{
SimpleAttributeSet keyWord = new SimpleAttributeSet();

    chat.insertString(chat.getLength(), "<User>"+input, keyWord );
    
           SimpleAttributeSet keyWord2 = new SimpleAttributeSet();
           
            SimpleAttributeSet Keyword2 = keyWord;
    
    if (persona.matches("Vader"))
    { StyleConstants.setForeground(keyWord, Color.RED);
   chat.insertString(chat.getLength(),  "\n<"+persona+">",Keyword2);} 
            else{ StyleConstants.setForeground(keyWord, Color.BLUE);
   chat.insertString(chat.getLength(),  "\n<"+persona+">",Keyword2);}
   
    StyleConstants.setForeground(keyWord, Color.BLACK);
   chat.insertString(chat.getLength(),output+"\n",Keyword2);
}
catch(Exception e) { System.out.println(e); }
       
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new NewJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane chatbox;
    private javax.swing.JTextField inputbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton send;
    private javax.swing.JToggleButton switcher;
    // End of variables declaration//GEN-END:variables
}
